# Generated by Django 2.2 on 2022-01-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote_likes',
            field=models.ManyToManyField(related_name='liked_quotes', to='login_and_reg_app.User'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='login_and_reg_app.User'),
        ),
    ]
