# Generated by Django 2.2 on 2022-01-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='user',
        ),
    ]
